### ISSUE TITLE
Demo_deblur_real_application

### ISSUE THREAD

**Issue by dadachongzi** [cszn/IRCNN#10]
错误使用 edgetaper
需要的 第 2 个输入, PSF, 应为 非零。

出错 edgetaper>parse_inputs (line 128)
validateattributes(PSF,{'uint8','uint16','int16','double','single'},...

出错 edgetaper (line 34)
[I, PSF, sizeI, classI, sizePSF, numNSdim] = parse_inputs(varargin{:});

出错 Demo_deblur_real_application (line 76)
    y = edgetaper(y, k);

看来您回答别人的要有模糊核，您的样例的模糊核不是文件里就有吗，而且也都出来了，为啥还是有这个问题啊？
希望百忙之中抽空解决一下，谢谢了

**Comment by cszn** [comment]
你好, 用断点排查一下k是否有效. 我运行没有出现这样的问题.

**Comment by akafen** [comment]
hello,想问一下你这个问题解决了吗，我是在Linux上运行该demo的，也是不行啊

**Comment by cszn** [comment]
matlab版本的问题, edgetaper不允许kernel包含0值. matlab2015b没有问题, 新版本可能有问题, 解决方法有两种: (1) k(k==0) = 1e-10; (2) 不用edgetaper, 已经更新代码https://github.com/cszn/IRCNN/blob/master/Demo_deblur_real_application.m
注意需要用到https://github.com/cszn/IRCNN/tree/master/utilities 添加的两个函数 wrap_boundary_liu.m和 opt_fft_size.m
