### ISSUE TITLE
About “Demo_inpaint” application

### ISSUE THREAD

**Issue by mylifeyouwill** [cszn/IRCNN#11]
In that application, you use Shepard initialize to fit the picture. But in Shepard function, you use mask as one of its parameter.

I'm very confused about how can we get a picture's "mask.png".Totally we just get a picture without its mask. If your paper just ignores mask's extract just because it is so easy for the paper?

Maybe my problem was so noob.... Sorry about that because I'm new to the CNN...

If you have free time to answer, thank you for your patience!!!

**Comment by cszn** [comment]
In most inpainting literature, the mask is given. On the other hand, it is easy to get the mask.
