### ISSUE TITLE
How to upscale a noisy image in your code

### ISSUE THREAD

**Issue by Paper99** [cszn/IRCNN#16]
Thank you for your replying.

**Comment by cszn** [comment]
Use `Demo_SISR_direct_downsampler_real_application.m` to produce the above SISR results.

**Comment by Paper99** [comment]
If I want to test your code on benchmark (_eg._ Set5, Set14). How could I get the results for upscaling the nosiy images? Use  `Demo_SISR_direct_downsampler_real_application.m` or `Demo_SISR_direct_downsampler_RGB.m` ? 
Thank you for your replying.
