### ISSUE TITLE
CUDA Ready GPU is a requirement?(Undefined function or variable 'vl_simplenn_tidy'.)

### ISSUE THREAD

**Issue by my1347** [cszn/IRCNN#6]
Dear cszn:
Hi, you are doing really a good job. But I running into and error.
Does it mean I still need a Cuda Support GPU even if I set "use GPU =0" ?
Undefined function or variable 'vl_simplenn_tidy'.
![image](https://user-images.githubusercontent.com/5409816/35851689-b7f0043c-0b63-11e8-8639-19a0f4bcb51d.png)

**Comment by cszn** [comment]
Hi, you should install [Matconvnet](http://www.vlfeat.org/matconvnet/) first.

**Comment by my1347** [comment]
@cszn 多谢老铁
