### ISSUE TITLE
Could you help me fix the problem

### ISSUE THREAD

**Issue by akafen** [cszn/IRCNN#8]
Error using edgetaper
Expected input number 2, PSF, to be nonzero.

Error in edgetaper>parse_inputs (line 128)
validateattributes(PSF,{'uint8','uint16','int16','double','single'},...

Error in edgetaper (line 34)
[I, PSF, sizeI, classI, sizePSF, numNSdim] = parse_inputs(varargin{:});

Error in Demo_deblur_real_application (line 76)
    y = edgetaper(y,k);

**Comment by cszn** [comment]
Check whether k is a valid kernel.

**Comment by akafen** [comment]
I just run the demo,but it could not work,the problem is what I said

**Comment by cszn** [comment]
Pay attention to "Expected input number 2, PSF, to be nonzero."

**Comment by pingfansong** [comment]
PSF is required not to contain zero elements by the function validateattributes(PSF,{'uint8','uint16','int16','double','single'},...

So, you need to check PSF to make sure it does not contain zeros.
